trigger:
- master

pool:
  name: Default

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

# Install NuGet
- task: NuGetToolInstaller@1

# Restore packages
- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

# Build solution
- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=FileSystem /p:PublishUrl=$(Build.ArtifactStagingDirectory)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

# 🔴 Publish Web API
- task: DotNetCoreCLI@2
  inputs:
    command: publish
    projects: '**/*WebAPI*.csproj'
    arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: false

# Zip publish output
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/_PublishedWebsites'
    includeRootFolder: false
    archiveType: zip
    archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'

# Publish artifact
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: drop

# Deploy to Azure App Service
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'solid-web-api'
    appType: webApp
    appName: SOLID-WebAPI
    package: '$(Build.ArtifactStagingDirectory)/webapi.zip'